<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<CompressionEnabled>false</CompressionEnabled>
	</PropertyGroup>

	<PropertyGroup>
		<TrimMode>partial</TrimMode>
		<PublishTrimmed>false</PublishTrimmed>
		<SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Markdig" Version="0.41.3" />
		<PackageReference Include="Markdown.ColorCode" Version="3.0.0" />
		<PackageReference Include="Radzen.Blazor" Version="7.1.2" />
		<PackageReference Include="SpawnDev.Blazor.UnitTesting" Version="2.4.0" />
		<PackageReference Include="SpawnDev.BlazorJS" Version="2.58.0" />
		<PackageReference Include="SpawnDev.BlazorJS.WebWorkers" Version="2.35.0" />
	</ItemGroup>

	<!-- SpawnDev.BlazorJS.WebWorkers config -->
	<PropertyGroup>
		<!-- 
		WebWorkerPatchFramework
		- To run Blazor WASM in non-window scopes (DedicatedWorker, SharedWorker, ServiceWorker) Blazor framework files need to be patched.
		- Patching can be done at runtime in Javascript, or at build time. 
		- Build time patching gives better performance and works with stricter ContentSecurityPolicy rules
		- false - patch at runtime (current default)
		- true  - patch during build
		-->
		<WebWorkerPatchFramework>false</WebWorkerPatchFramework>
	</PropertyGroup>

</Project>

